#!/bin/bash
# This script is written and provided as is by Jamie Charleston - Senior Sales Engineer at CloudLinux for use with TuxCare ePortal POV.
# This package is for assisting organizations that need to prepare a CentOS 7 server for KernelCare(+) POC. This package is going to
# download the CentOS 7.0 kernel as well as glibc and openssl packages, install them and reboot the server. This should prepare your server
# for visible patches to your server, live and in memory


base64 -d <<<"X19fX19fX19fICAgICAgICAgICAgICAgICAgIF9fX19fX18gIF9fX19fX18gIF9fX19fX18gIF9f
X19fX18gICAgX19fX19fXyAgX19fX19fXyAgX19fX19fXyAgX19fX19fXyBfX19fX19fX18gX19f
X19fXyAgXyAgICAgICAKXF9fICAgX18vfFwgICAgIC98fFwgICAgIC98KCAgX19fXyBcKCAgX19f
ICApKCAgX19fXyApKCAgX19fXyBcICAoICBfX19fIFwoICBfX19fICkoICBfX18gICkoICBfX19f
IClcX18gICBfXy8oICBfX18gICkoIFwgICAgICAKICAgKSAoICAgfCApICAgKCB8KCBcICAgLyAp
fCAoICAgIFwvfCAoICAgKSB8fCAoICAgICl8fCAoICAgIFwvICB8ICggICAgXC98ICggICAgKXx8
ICggICApIHx8ICggICAgKXwgICApICggICB8ICggICApIHx8ICggICAgICAKICAgfCB8ICAgfCB8
ICAgfCB8IFwgKF8pIC8gfCB8ICAgICAgfCAoX19fKSB8fCAoX19fXyl8fCAoX18gICAgICB8IChf
XyAgICB8IChfX19fKXx8IHwgICB8IHx8IChfX19fKXwgICB8IHwgICB8IChfX18pIHx8IHwgICAg
ICAKICAgfCB8ICAgfCB8ICAgfCB8ICApIF8gKCAgfCB8ICAgICAgfCAgX19fICB8fCAgICAgX18p
fCAgX18pICAgICB8ICBfXykgICB8ICBfX19fXyl8IHwgICB8IHx8ICAgICBfXykgICB8IHwgICB8
ICBfX18gIHx8IHwgICAgICAKICAgfCB8ICAgfCB8ICAgfCB8IC8gKCApIFwgfCB8ICAgICAgfCAo
ICAgKSB8fCAoXCAoICAgfCAoICAgICAgICB8ICggICAgICB8ICggICAgICB8IHwgICB8IHx8IChc
ICggICAgICB8IHwgICB8ICggICApIHx8IHwgICAgICAKICAgfCB8ICAgfCAoX19fKSB8KCAvICAg
XCApfCAoX19fXy9cfCApICAgKCB8fCApIFwgXF9ffCAoX19fXy9cICB8IChfX19fL1x8ICkgICAg
ICB8IChfX18pIHx8ICkgXCBcX18gICB8IHwgICB8ICkgICAoIHx8IChfX19fL1wKICAgKV8oICAg
KF9fX19fX18pfC8gICAgIFx8KF9fX19fX18vfC8gICAgIFx8fC8gICBcX18vKF9fX19fX18vICAo
X19fX19fXy98LyAgICAgICAoX19fX19fXyl8LyAgIFxfXy8gICApXyggICB8LyAgICAgXHwoX19f
X19fXy8KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAK"
echo
echo
echo Welcome to the KernelCare ePortal installation Process.
echo This script is written and provided as is by Jamie Charleston - Senior Sales Engineer at CloudLinux for use with TuxCare ePortal POV.
echo "This package is for assisting organizations that need to prepare a CentOS 7 server for KernelCare POV. This package is going to"
echo download the CentOS 7.0 kernel as well as glibc and openssl packages, install them and reboot the server. This should prepare your server
echo for visible patches to your server, live and in memory. 

echo
echo


echo "Please confirm you are ready revert your CentOS 7 server to old packages and that you understand we will reboot the server at the end of the process?"
echo "Please type 'yes' or 'no'"

read varAnswer
a=$varAnswer

if [ $a == yes ]
then
     clear
     echo We are now going to configure ePortal to work with KernelCare+ packages
     sleep 2s
     echo We are going to download our base userspace file...

     wget http://vault.centos.org/7.0.1406/os/x86_64/Packages/kernel-3.10.0-123.el7.x86_64.rpm
     wget http://vault.centos.org/7.0.1406/os/x86_64/Packages/openssl-1.0.1e-34.el7.x86_64.rpm
     wget http://vault.centos.org/7.0.1406/os/x86_64/Packages/openssl-libs-1.0.1e-34.el7.x86_64.rpm
     wget http://vault.centos.org/7.0.1406/os/x86_64/Packages/openssl-1.0.1e-34.el7.x86_64.rpm
     wget http://vault.centos.org/7.0.1406/os/x86_64/Packages/openssl-libs-1.0.1e-34.el7.x86_64.rpm
     echo ""
     echo ""
     echo Files were downloaded successfully
     echo ""
     echo "We will now install older packages"

       rpm -ihv *.rpm --force
       

      echo ""
      echo ""
      echo   "Files have been installed, we will now reboot your server for the new kernel and packages to start working."

     sleep 5s
     
      reboot

       
  else
    clear
    echo We are complete and have not made any modification to your server
    sleep 5s

  fi

